version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      commander:
        patterns:
          - commander
          - "@commander-js/extra-typings"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
