id: ch-bfe
name: Swiss Federal Office of Energy
level: AUTHORITATIVE
jurisdictions:
  - CH
homepageUrl: https://www.suisseenergie.ch/programmes/infrastructure-de-recharge/outils/identifiant-pour-les-cpo-et-les-emp/registre-suisse-des-identifiants/
