id: cy-ems
name: Department of Electrical and Mechanical Services
level: AUTHORITATIVE
jurisdictions:
  - CY
homepageUrl: https://www.mcw.gov.cy/mcw/ems/ems.nsf/All/D764FAE19922743BC2258DAA002FA4BC?OpenDocument
