id: ie-tii
name: Transport Infrastructure Ireland
level: AUTHORITATIVE
jurisdictions:
  - IE
homepageUrl: https://www.tii.ie/en/roads-tolling/alt-fuel-projects-unit/alt-fuels-data-office/register-idro/
