id: se-energimyndigheten
name: Swedish Energy Agency
level: AUTHORITATIVE
jurisdictions:
  - SE
homepageUrl: https://www.energimyndigheten.se/klimat/transporter/laddinfrastruktur/identification-registration-organisation-idro/
